# Generated by Django 5.0 on 2023-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
