# Generated by Django 5.0 on 2023-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0003_remove_attempt_question_asked_remove_attempt_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time_taken',
            field=models.IntegerField(default=1),
        ),
    ]
