# Generated by Django 5.0 on 2023-12-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0006_attempt_user_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='question_asked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='timestablesapp.question'),
        ),
    ]
