# Generated by Django 5.0 on 2023-12-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0010_times_table_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
