# Generated by Django 5.0 on 2023-12-15 17:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0012_teacher_student_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_tested', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=12), django.core.validators.MinValueValidator(limit_value=2)])),
                ('tested', models.BooleanField(default=True)),
                ('user_tested', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
