# Generated by Django 5.0 on 2023-12-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0013_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='tested',
            new_name='set',
        ),
    ]
