# Generated by Django 5.0 on 2023-12-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0014_rename_tested_test_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='question_tested',
            new_name='table_tested',
        ),
    ]
