# Generated by Django 5.0 on 2023-12-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0017_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.DeleteModel(
            name='Times_table_assigned',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='timestablesapp.teacher'),
        ),
    ]
