# Generated by Django 5.0 on 2023-12-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestablesapp', '0022_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timestablesapp.admin'),
        ),
    ]
